//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Shreds.Fax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ReceivedFaxQueueProcessorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReceivedFaxQueueProcessorSettings defaultInstance = ((ReceivedFaxQueueProcessorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReceivedFaxQueueProcessorSettings())));
        
        public static ReceivedFaxQueueProcessorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Batch size for processor to retrieve.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Batch size for processor to retrieve.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BatchSize {
            get {
                return ((int)(this["BatchSize"]));
            }
        }
        
        /// <summary>
        /// Processor thread sleep time in seconds.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Processor thread sleep time in seconds.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SleepTime {
            get {
                return ((int)(this["SleepTime"]));
            }
        }
        
        /// <summary>
        /// Dictates processor action regarding spam fax items.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Dictates processor action regarding spam fax items.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreSpam {
            get {
                return ((bool)(this["IgnoreSpam"]));
            }
        }
        
        /// <summary>
        /// The directory where the incoming faxes are stored.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The directory where the incoming faxes are stored.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\All Users\\Application Data\\ClearCanvas_Inc\\IncomingFax")]
        public string IncomingFaxDirectory {
            get {
                return ((string)(this["IncomingFaxDirectory"]));
            }
        }
        
        /// <summary>
        /// Customizable fax metadata file extension.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Customizable fax metadata file extension.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fmd")]
        public string MetaDataFileExtension {
            get {
                return ((string)(this["MetaDataFileExtension"]));
            }
        }
        
        /// <summary>
        /// Image data file extension (e.g. pdf, tif, jpg)
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Image data file extension (e.g. pdf, tif, jpg)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdf")]
        public string ImageDataFileExtension {
            get {
                return ((string)(this["ImageDataFileExtension"]));
            }
        }
        
        /// <summary>
        /// The directory where the faxes with errors are stored.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The directory where the faxes with errors are stored.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\All Users\\Application Data\\ClearCanvas_Inc\\ErrorFax")]
        public string ErrorFaxDirectory {
            get {
                return ((string)(this["ErrorFaxDirectory"]));
            }
        }
        
        /// <summary>
        /// The delimiters used to separate field name and value in the meta data file.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The delimiters used to separate field name and value in the meta data file.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string MetaDataDelimiters {
            get {
                return ((string)(this["MetaDataDelimiters"]));
            }
        }
    }
}
