//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class NSSeeting : global::System.Configuration.ApplicationSettingsBase {
        
        private static NSSeeting defaultInstance = ((NSSeeting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new NSSeeting())));
        
        public static NSSeeting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Healthcare")]
        public string Entity_NS {
            get {
                return ((string)(this["Entity_NS"]));
            }
            set {
                this["Entity_NS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Ris.Application.Common")]
        public string Common_NS {
            get {
                return ((string)(this["Common_NS"]));
            }
            set {
                this["Common_NS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Ris.Application.Services")]
        public string Service_NS {
            get {
                return ((string)(this["Service_NS"]));
            }
            set {
                this["Service_NS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Ris.Client")]
        public string Component_NS {
            get {
                return ((string)(this["Component_NS"]));
            }
            set {
                this["Component_NS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClearCanvas.Ris.Client.View.Winforms")]
        public string ComponentControl_NS {
            get {
                return ((string)(this["ComponentControl_NS"]));
            }
            set {
                this["ComponentControl_NS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Myprojects\\Ris2sp1")]
        public string ProjectRoot {
            get {
                return ((string)(this["ProjectRoot"]));
            }
            set {
                this["ProjectRoot"] = value;
            }
        }
    }
}
