//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Shreds.Fax {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ReceivedFaxShredSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReceivedFaxShredSettings defaultInstance = ((ReceivedFaxShredSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReceivedFaxShredSettings())));
        
        public static ReceivedFaxShredSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Number of items to pull from queue per read
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of items to pull from queue per read")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BatchSize {
            get {
                return ((int)(this["BatchSize"]));
            }
        }
        
        /// <summary>
        /// Number of seconds to sleep when queue is empty
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of seconds to sleep when queue is empty")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int EmptyQueueSleepTime {
            get {
                return ((int)(this["EmptyQueueSleepTime"]));
            }
        }
        
        /// <summary>
        /// Number of seconds that must elapse before a failed item is retried
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Number of seconds that must elapse before a failed item is retried")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int FailedItemRetryDelay {
            get {
                return ((int)(this["FailedItemRetryDelay"]));
            }
        }
        
        /// <summary>
        /// Maximum number of retries before a failed item is marked as failed.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Maximum number of retries before a failed item is marked as failed.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FailedItemRetryCount {
            get {
                return ((int)(this["FailedItemRetryCount"]));
            }
        }
        
        /// <summary>
        /// Customizable fax metadata file extension.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Customizable fax metadata file extension.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fmd")]
        public string MetaDataFileExtension {
            get {
                return ((string)(this["MetaDataFileExtension"]));
            }
        }
        
        /// <summary>
        /// Image data file extension (e.g. pdf, tif, jpg)
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Image data file extension (e.g. pdf, tif, jpg)")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdf")]
        public string ImageDataFileExtension {
            get {
                return ((string)(this["ImageDataFileExtension"]));
            }
        }
        
        /// <summary>
        /// The delimiters used to separate field name and value in the meta data file.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The delimiters used to separate field name and value in the meta data file.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("=")]
        public string MetaDataDelimiters {
            get {
                return ((string)(this["MetaDataDelimiters"]));
            }
        }
        
        /// <summary>
        /// The directory where the incoming faxes are stored.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The directory where the incoming faxes are stored.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\All Users\\Application Data\\ClearCanvas_Inc\\IncomingFax")]
        public string IncomingFaxDirectory {
            get {
                return ((string)(this["IncomingFaxDirectory"]));
            }
        }
        
        /// <summary>
        /// The directory where the incoming faxes are stored after the fax storage work queue items are created
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("The directory where the incoming faxes are stored after the fax storage work queu" +
            "e items are created")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Documents and Settings\\All Users\\Application Data\\ClearCanvas_Inc\\ReceivedFaxW" +
            "orkQueueItem")]
        public string ReceivedFaxWorkQueueItemDirectory {
            get {
                return ((string)(this["ReceivedFaxWorkQueueItemDirectory"]));
            }
        }
    }
}
