//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Material.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Material.Client.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Save Contacts Right now, Try again Later or contact Administrator for more detail..
        /// </summary>
        internal static string ExceptionSave {
            get {
                return ResourceManager.GetString("ExceptionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Print Invoices/Transaction Detail?.
        /// </summary>
        internal static string MessageConfirmPrintInvoice {
            get {
                return ResourceManager.GetString("MessageConfirmPrintInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Contacts.
        /// </summary>
        internal static string TitleAddContact {
            get {
                return ResourceManager.GetString("TitleAddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Material Lot.
        /// </summary>
        internal static string TitleAddMaterialLot {
            get {
                return ResourceManager.GetString("TitleAddMaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Medicine Counter.
        /// </summary>
        internal static string TitleAddMedicineCounter {
            get {
                return ResourceManager.GetString("TitleAddMedicineCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new warehouse.
        /// </summary>
        internal static string TitleAddWarehouse {
            get {
                return ResourceManager.GetString("TitleAddWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string TitleContactAddressColumn {
            get {
                return ResourceManager.GetString("TitleContactAddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TitleContactCodeColumn {
            get {
                return ResourceManager.GetString("TitleContactCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail information.
        /// </summary>
        internal static string TitleContactContactDetailInformationColumn {
            get {
                return ResourceManager.GetString("TitleContactContactDetailInformationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string TitleContactDeactivatedColumn {
            get {
                return ResourceManager.GetString("TitleContactDeactivatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TitleContactNameColumn {
            get {
                return ResourceManager.GetString("TitleContactNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Management.
        /// </summary>
        internal static string TitleContactSummary {
            get {
                return ResourceManager.GetString("TitleContactSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TitleMaterialLotDescriptionColumn {
            get {
                return ResourceManager.GetString("TitleMaterialLotDescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string TitleMaterialLotIdColumn {
            get {
                return ResourceManager.GetString("TitleMaterialLotIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string TitleMaterialLotInputDateColumn {
            get {
                return ResourceManager.GetString("TitleMaterialLotInputDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Lots.
        /// </summary>
        internal static string TitleMaterialLotSummary {
            get {
                return ResourceManager.GetString("TitleMaterialLotSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Code.
        /// </summary>
        internal static string TitleMedicineCounterCodeColumn {
            get {
                return ResourceManager.GetString("TitleMedicineCounterCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TitleMedicineCounterNameColumn {
            get {
                return ResourceManager.GetString("TitleMedicineCounterNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Counter Management.
        /// </summary>
        internal static string TitleMedicineCounterSummary {
            get {
                return ResourceManager.GetString("TitleMedicineCounterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Code.
        /// </summary>
        internal static string TitleStockTransactionCodeColumn {
            get {
                return ResourceManager.GetString("TitleStockTransactionCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TitleStockTransactionDescriptionColumn {
            get {
                return ResourceManager.GetString("TitleStockTransactionDescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction management.
        /// </summary>
        internal static string TitleStockTransactionSummary {
            get {
                return ResourceManager.GetString("TitleStockTransactionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string TitleStockTransactionTransactionDateColumn {
            get {
                return ResourceManager.GetString("TitleStockTransactionTransactionDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string TitleStockTransactionTypeColumn {
            get {
                return ResourceManager.GetString("TitleStockTransactionTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string TitleTransactionLineAmountColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineAmountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Code.
        /// </summary>
        internal static string TitleTransactionLineCodeColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Expire Date.
        /// </summary>
        internal static string TitleTransactionLineExpireDateColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineExpireDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Unit Price.
        /// </summary>
        internal static string TitleTransactionLineInputPriceColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineInputPriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Full Name.
        /// </summary>
        internal static string TitleTransactionLineNameColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate (%).
        /// </summary>
        internal static string TitleTransactionLineTaxColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineTaxColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        internal static string TitleTransactionLineUOMColumn {
            get {
                return ResourceManager.GetString("TitleTransactionLineUOMColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Contact - {0}.
        /// </summary>
        internal static string TitleUpdateContact {
            get {
                return ResourceManager.GetString("TitleUpdateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Material Lot - {0}.
        /// </summary>
        internal static string TitleUpdateMaterialLot {
            get {
                return ResourceManager.GetString("TitleUpdateMaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Medicine Counter - {0}.
        /// </summary>
        internal static string TitleUpdateMedicineCounter {
            get {
                return ResourceManager.GetString("TitleUpdateMedicineCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Warehouse - {0}.
        /// </summary>
        internal static string TitleUpdateWarehouse {
            get {
                return ResourceManager.GetString("TitleUpdateWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Code.
        /// </summary>
        internal static string TitleWarehouseCodeColumn {
            get {
                return ResourceManager.GetString("TitleWarehouseCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Contact.
        /// </summary>
        internal static string TitleWarehouseContactDetailInformationColumn {
            get {
                return ResourceManager.GetString("TitleWarehouseContactDetailInformationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TitleWarehouseNameColumn {
            get {
                return ResourceManager.GetString("TitleWarehouseNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Management.
        /// </summary>
        internal static string TitleWarehouseSummary {
            get {
                return ResourceManager.GetString("TitleWarehouseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string ToolContacts {
            get {
                return ResourceManager.GetString("ToolContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Stocking Medicines.
        /// </summary>
        internal static string ToolInstockingMedicine {
            get {
                return ResourceManager.GetString("ToolInstockingMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Lot.
        /// </summary>
        internal static string ToolMaterialLot {
            get {
                return ResourceManager.GetString("ToolMaterialLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Counter.
        /// </summary>
        internal static string ToolMedicineCounter {
            get {
                return ResourceManager.GetString("ToolMedicineCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        internal static string ToolWarehouse {
            get {
                return ResourceManager.GetString("ToolWarehouse", resourceCulture);
            }
        }
    }
}
