//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ReportSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReportSetting defaultInstance = ((ReportSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportSetting())));
        
        public static ReportSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bệnh Viện Cấp Cứu Trương Vương")]
        public string HospitalName {
            get {
                return ((string)(this["HospitalName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thông Tin Bệnh Nhân")]
        public string ReportTitile {
            get {
                return ((string)(this["ReportTitile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("266, Lý Thường Kiệt P. 14, Q. 10")]
        public string Address {
            get {
                return ((string)(this["Address"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(08)38642750")]
        public string Phone {
            get {
                return ((string)(this["Phone"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Website {
            get {
                return ((string)(this["Website"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logo.jpg")]
        public string LogoImage {
            get {
                return ((string)(this["LogoImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PdfPatientReport.rpt")]
        public string ReportUrl {
            get {
                return ((string)(this["ReportUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.1.29\\biti-data\\Public\\TelPacsV2.0\\HospitalInfo")]
        public string HospitalInfoDirName {
            get {
                return ((string)(this["HospitalInfoDirName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StudyHistory.rpt")]
        public string ViewStudyhistoryTemplate {
            get {
                return ((string)(this["ViewStudyhistoryTemplate"]));
            }
        }
    }
}
