//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Shreds.MwlServer.CCRisQueryConnector.Uhn {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class MwlFilterSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MwlFilterSettings defaultInstance = ((MwlFilterSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MwlFilterSettings())));
        
        public static MwlFilterSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Stores the procedure type ID of a list of Breast Imaging procedures that are considered to be US modality in the DICOM sense.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Stores the procedure type ID of a list of Breast Imaging procedures that are cons" +
            "idered to be US modality in the DICOM sense.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0114007,0114008,0114009,0114012")]
        public string BreastImagingUltrasoundProcedureIDs {
            get {
                return ((string)(this["BreastImagingUltrasoundProcedureIDs"]));
            }
        }
        
        /// <summary>
        /// Stores a list of comma separated values that describes the rules for replacing DICOM tag values in the return MWL result messages.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Stores a list of comma separated values that describes the rules for replacing DI" +
            "COM tag values in the return MWL result messages.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-- This setting contains a list of tag replacement rules in the following format.  Tabs and spaces will be trimmed.
-- AETitle, (group, element), ""New Value""
-- The new value must match the value representation (VR) of the particular Dicom tag being written
-- Otherwise the new value will not be written.

ModalitySCU, (0040,0001), ""ModalitySCU""	-- Scheduled Station AE Title")]
        public string TagReplacementRules {
            get {
                return ((string)(this["TagReplacementRules"]));
            }
        }
    }
}
