//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.View.WinForms.Billing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Ris.Client.View.WinForms.Billing.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information ({0}).
        /// </summary>
        internal static string BillingInfoText {
            get {
                return ResourceManager.GetString("BillingInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is cancelled sucessfully.
        /// </summary>
        internal static string CancelOrderFinished {
            get {
                return ResourceManager.GetString("CancelOrderFinished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClearFilterMini {
            get {
                object obj = ResourceManager.GetObject("ClearFilterMini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClearFilterSmall {
            get {
                object obj = ResourceManager.GetObject("ClearFilterSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance is collected.
        /// </summary>
        internal static string CollectedInsurance {
            get {
                return ResourceManager.GetString("CollectedInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed waiting insurance successfully.
        /// </summary>
        internal static string CollectScreenConfirmInsurance {
            get {
                return ResourceManager.GetString("CollectScreenConfirmInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Insurance is Rejected.
        /// </summary>
        internal static string CollectScreenRejectedInsurance {
            get {
                return ResourceManager.GetString("CollectScreenRejectedInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the Price will changed when the Primary currency is Changed.
        /// </summary>
        internal static string ConfirmPrimaryCurrencyChanged {
            get {
                return ResourceManager.GetString("ConfirmPrimaryCurrencyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Exchange Rate will be changed base on when Primary Ex-Rate Currency is changed.
        /// </summary>
        internal static string ConfirmPrimaryExRateCurrencyChanged {
            get {
                return ResourceManager.GetString("ConfirmPrimaryExRateCurrencyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string CurrencyDisplayFormat {
            get {
                return ResourceManager.GetString("CurrencyDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose Discount/insurance Type, Type and Discount/insurance Amount Or Data Invalid.
        /// </summary>
        internal static string DiscountInsuranceItemRuleNotSelected {
            get {
                return ResourceManager.GetString("DiscountInsuranceItemRuleNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or many selected procedure type conflicts with an existing procedure..
        /// </summary>
        internal static string DiscountInsuranceRulesExisting {
            get {
                return ResourceManager.GetString("DiscountInsuranceRulesExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Least one item is selected.
        /// </summary>
        internal static string DropDownMandatorySelected {
            get {
                return ResourceManager.GetString("DropDownMandatorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price.
        /// </summary>
        internal static string FIXEDPRICE {
            get {
                return ResourceManager.GetString("FIXEDPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Closed Successfully!.
        /// </summary>
        internal static string InvoiceClosed {
            get {
                return ResourceManager.GetString("InvoiceClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number cannot be null.
        /// </summary>
        internal static string InvoiceNumberInvalid {
            get {
                return ResourceManager.GetString("InvoiceNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Insurance Confirm Pending.
        /// </summary>
        internal static string NotPending {
            get {
                return ResourceManager.GetString("NotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure is not pending.
        /// </summary>
        internal static string NotPendingInsurance {
            get {
                return ResourceManager.GetString("NotPendingInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number format invalid.
        /// </summary>
        internal static string NumberFormatInvalid {
            get {
                return ResourceManager.GetString("NumberFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Cancel.
        /// </summary>
        internal static string OrderCancel {
            get {
                return ResourceManager.GetString("OrderCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is not selected.
        /// </summary>
        internal static string OrderEmpty {
            get {
                return ResourceManager.GetString("OrderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is Paid.
        /// </summary>
        internal static string OrderPaid {
            get {
                return ResourceManager.GetString("OrderPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is UnPaid.
        /// </summary>
        internal static string OrderUnPaid {
            get {
                return ResourceManager.GetString("OrderUnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is package procedure, cannot  apply insurance or discount.
        /// </summary>
        internal static string PackageProcedureEditError {
            get {
                return ResourceManager.GetString("PackageProcedureEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Package procedure.
        /// </summary>
        internal static string PackgeProcedure {
            get {
                return ResourceManager.GetString("PackgeProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for confirm.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string PERCENTAGE {
            get {
                return ResourceManager.GetString("PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is re-Confirmed sucessfully.
        /// </summary>
        internal static string ReConfirmOrderFinished {
            get {
                return ResourceManager.GetString("ReConfirmOrderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Amount.
        /// </summary>
        internal static string REDUCEAMOUNT {
            get {
                return ResourceManager.GetString("REDUCEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform this operation at the moment, contact administrator for more detail.
        /// </summary>
        internal static string SaveInvoiceFailed {
            get {
                return ResourceManager.GetString("SaveInvoiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money is collected sucessfully.
        /// </summary>
        internal static string SaveInvoiceSuccessful {
            get {
                return ResourceManager.GetString("SaveInvoiceSuccessful", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SearchToolSmall {
            get {
                object obj = ResourceManager.GetObject("SearchToolSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money received is not enough pay for this invoice.
        /// </summary>
        internal static string Totalreceivednotenough {
            get {
                return ResourceManager.GetString("Totalreceivednotenough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are discard.
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrent Number Format.
        /// </summary>
        internal static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
    }
}
