//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.Billing.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Ris.Client.Billing.Tools.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Cash.
        /// </summary>
        internal static string CollectCash {
            get {
                return ResourceManager.GetString("CollectCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Price.
        /// </summary>
        internal static string DiscountPrice {
            get {
                return ResourceManager.GetString("DiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Price.
        /// </summary>
        internal static string InsurancePrice {
            get {
                return ResourceManager.GetString("InsurancePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Price.
        /// </summary>
        internal static string ItemPrice {
            get {
                return ResourceManager.GetString("ItemPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Category.
        /// </summary>
        internal static string ProcedureCategory {
            get {
                return ResourceManager.GetString("ProcedureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Options.
        /// </summary>
        internal static string TitleBillingOptions {
            get {
                return ResourceManager.GetString("TitleBillingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Manager.
        /// </summary>
        internal static string TitleCurrencyManager {
            get {
                return ResourceManager.GetString("TitleCurrencyManager", resourceCulture);
            }
        }
    }
}
