//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Ris.Client.Billing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Ris.Client.Billing.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Discounts.
        /// </summary>
        internal static string AddNewObjectSummary {
            get {
                return ResourceManager.GetString("AddNewObjectSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string ColumnCurrencyCode {
            get {
                return ResourceManager.GetString("ColumnCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Format.
        /// </summary>
        internal static string ColumnCurrencyCustomFormat {
            get {
                return ResourceManager.GetString("ColumnCurrencyCustomFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactived.
        /// </summary>
        internal static string ColumnCurrencyDeactivated {
            get {
                return ResourceManager.GetString("ColumnCurrencyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Locale.
        /// </summary>
        internal static string ColumnCurrencyDisplaylocale {
            get {
                return ResourceManager.GetString("ColumnCurrencyDisplaylocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string ColumnCurrencyName {
            get {
                return ResourceManager.GetString("ColumnCurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ColumnDiscountAmount {
            get {
                return ResourceManager.GetString("ColumnDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Type.
        /// </summary>
        internal static string ColumnDiscountAmountType {
            get {
                return ResourceManager.GetString("ColumnDiscountAmountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Code.
        /// </summary>
        internal static string ColumnDiscountClassCode {
            get {
                return ResourceManager.GetString("ColumnDiscountClassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ColumnDiscountClassName {
            get {
                return ResourceManager.GetString("ColumnDiscountClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Type.
        /// </summary>
        internal static string ColumnDiscountClassType {
            get {
                return ResourceManager.GetString("ColumnDiscountClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ColumnDiscountExpireDate {
            get {
                return ResourceManager.GetString("ColumnDiscountExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ColumnDiscountStartDate {
            get {
                return ResourceManager.GetString("ColumnDiscountStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ColumnInsuranceAmount {
            get {
                return ResourceManager.GetString("ColumnInsuranceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Type.
        /// </summary>
        internal static string ColumnInsuranceAmountType {
            get {
                return ResourceManager.GetString("ColumnInsuranceAmountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Code.
        /// </summary>
        internal static string ColumnInsuranceClassCode {
            get {
                return ResourceManager.GetString("ColumnInsuranceClassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        internal static string ColumnInsuranceClassName {
            get {
                return ResourceManager.GetString("ColumnInsuranceClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Type.
        /// </summary>
        internal static string ColumnInsuranceClassType {
            get {
                return ResourceManager.GetString("ColumnInsuranceClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ColumnInsuranceExpireDate {
            get {
                return ResourceManager.GetString("ColumnInsuranceExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ColumnInsuranceStartDate {
            get {
                return ResourceManager.GetString("ColumnInsuranceStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary Currency.
        /// </summary>
        internal static string ColumnIsPrimaryCurrency {
            get {
                return ResourceManager.GetString("ColumnIsPrimaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Primary Ex-Rate Currency.
        /// </summary>
        internal static string ColumnIsPrimaryExRateCurrency {
            get {
                return ResourceManager.GetString("ColumnIsPrimaryExRateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate To Primary Ex-Rate Currency({0}).
        /// </summary>
        internal static string ColumnRateToPrimaryCurrency {
            get {
                return ResourceManager.GetString("ColumnRateToPrimaryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Primary Currency And Primary Ex-Rate Currency.
        /// </summary>
        internal static string CurrencyDeleteError {
            get {
                return ResourceManager.GetString("CurrencyDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require field invalid: Currency Code, Currency Name  and Rate to Primary Ex-Rate Currency must be greater than 0.
        /// </summary>
        internal static string CurrencyValidateRequireFieldError {
            get {
                return ResourceManager.GetString("CurrencyValidateRequireFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while saving currency, try again later..
        /// </summary>
        internal static string ExceptionSaveCurrencyError {
            get {
                return ResourceManager.GetString("ExceptionSaveCurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Price.
        /// </summary>
        internal static string FIXEDPRICE {
            get {
                return ResourceManager.GetString("FIXEDPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string PERCENTAGE {
            get {
                return ResourceManager.GetString("PERCENTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Amount.
        /// </summary>
        internal static string REDUCEAMOUNT {
            get {
                return ResourceManager.GetString("REDUCEAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Currency.
        /// </summary>
        internal static string TitleAddCurrency {
            get {
                return ResourceManager.GetString("TitleAddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing .
        /// </summary>
        internal static string TitleUpdateCurrency {
            get {
                return ResourceManager.GetString("TitleUpdateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating .
        /// </summary>
        internal static string UpdateObjectSummary {
            get {
                return ResourceManager.GetString("UpdateObjectSummary", resourceCulture);
            }
        }
    }
}
